<?php

namespace Faker\Provider\sq_XK;

class Address extends \Faker\Provider\Address
{
    protected static $street = [
        'UÇK',
        'Garibaldi',
        'Luan Haradinaj',
        'Fehmi Agani',
        'Bill Clinton',
        'Ilir Konushevci',
        'Agim Ramadani',
        'Xhemajl Prishtina',
        'Muharrem Fejza',
        'Rexhep Luci',
        'Migjeni',
        'Zahir Pajaziti',
        'Adem Jashari',
        'Dëshmorët e Kombit',
        'Hasan Prishtina',
        'Ismail Qemali',
        'Eqrem Çabej',
        'Vëllezërit Gërvalla',
        'Idriz Seferi',
        'Bekim Berisha',
        'Nënë Tereza',
        'Bajram Curri',
        'Skënderbeu',
        'Gani Elshani',
        'Lidhja e Prizrenit',
        'Marin Barleti',
        'Haxhi Zeka',
    ];

    protected static $cityFormats = [
        '{{municipality}}',
    ];

    protected static $streetNameFormats = [
        '{{street}}',
    ];

    protected static $streetAddressFormats = [
        '{{streetName}} {{buildingNumber}}',
    ];

    protected static $addressFormats = [
        "{{streetAddress}}\n{{city}} {{postcode}}",
    ];

    protected static $buildingNumber = ['%##', '%#', '%'];

    /**
     * https://en.wikipedia.org/wiki/Postal_codes_in_Kosovo
     */
    protected static $postcode = ['#####'];

    /**
     * https://sq.wikipedia.org/wiki/Lista_e_shteteve
     */
    protected static $country = [
        'Afganistani',
        'Afrika Qendrore',
        'Algjeria',
        'Andorra',
        'Angola',
        'Antigua dhe Barbuda',
        'Arabia Saudite',
        'Argjentina',
        'Armenia',
        'Australia',
        'Austria',
        'Azerbajxhani',
        'Bahamet',
        'Bahreini',
        'Bangladeshi',
        'Barbadosi',
        'Belgjika',
        'Beliza',
        'Benini',
        'Birmania',
        'Bjellorusia',
        'Bolivia',
        'Bosnja dhe Hercegovina',
        'Botsvana',
        'Brazili',
        'Bregu i Fildishtë',
        'Brunei',
        'Bullgaria',
        'Burkina Faso',
        'Burundi',
        'Butani',
        'Çadi',
        'Republika Çeke',
        'Danimarka',
        'Domenika',
        'Republika Dominikane',
        'Egjipti',
        'Ekuadori',
        'Emiratet e Bashkuara Arabe',
        'Eritrea',
        'Estonia',
        'Etiopia',
        'Federata Mikroneziane',
        'Filipinet',
        'Finlanda',
        'Fixhi',
        'Franca',
        'Gaboni',
        'Gambia',
        'Gana',
        'Grenada',
        'Greqia',
        'Guajana',
        'Guatemala',
        'Guinea',
        'Guinea Bisau',
        'Guinea Ekuatoriale',
        'Gjeorgjia',
        'Gjermania',
        'Haiti',
        'Holanda',
        'Hondurasi',
        'Hungaria',
        'India',
        'Indonezia',
        'Iraku',
        'Irani',
        'Irlanda',
        'Islanda',
        'Italia',
        'Izraeli',
        'Japonia',
        'Jemeni',
        'Jordania',
        'Republika Jugafrikane',
        'Kamboxhia',
        'Kameruni',
        'Kanadaja',
        'Katari',
        'Kazakistani',
        'Kenia',
        'Kepi i Gjelbër',
        'Kili',
        'Kina',
        'Kirgizistani',
        'Kiribati',
        'Kolumbia',
        'Komoret',
        'Kongo, Republika e',
        'Kongo, Republika Demokratike e',
        'Koreja e Jugut',
        'Koreja e Veriut',
        'Kosova',
        'Kosta Rika',
        'Kroacia',
        'Kuba',
        'Kuvajti',
        'Laosi',
        'Lesoto',
        'Letonia',
        'Libani',
        'Liberia',
        'Libia',
        'Lihtenshtajni',
        'Lituania',
        'Luksemburgu',
        'Madagaskari',
        'Malajzia',
        'Malavi',
        'Maldivet',
        'Mali',
        'Mali i Zi',
        'Malta',
        'Maroku',
        'Maqedonia e Veriut',
        'Ishujt Marshall',
        'Mauritania',
        'Mauritiusi',
        'Mbretëria e Bashkuar',
        'Anglia',
        'Irlanda Veriore',
        'Skocia',
        'Uellsi',
        'Moldavia',
        'Monako',
        'Mongolia',
        'Mozambiku',
        'Namibia',
        'Naurua',
        'Nepali',
        'Nigeri',
        'Nigeria',
        'Nikaragua',
        'Norvegjia',
        'Omani',
        'Pakistani',
        'Palau',
        'Palestina',
        'Panamaja',
        'Papua Guinea e Re',
        'Paraguaji',
        'Peruja',
        'Polonia',
        'Portugalia',
        'Qiproja',
        'Ruanda',
        'Rumania',
        'Rusia',
        'Salvadori',
        'Samoa',
        'San Marino',
        'Sao Tome dhe Principe',
        'Sejshellet',
        'Senegali',
        'Serbia',
        'Siera Leone',
        'Singapori',
        'Siria',
        'Sllovakia',
        'Sllovenia',
        'Ishujt Solomon',
        'Somalia',
        'Spanja',
        'Sri Lanka',
        'Suazilandi',
        'Sudani',
        'Sudani i Jugut',
        'Suedia',
        'Surinami',
        'Shën Kits dhe Nevis',
        'Shën Luçia',
        'Shën Vincenti dhe Grenadinet',
        'Shqipëria',
        'Shtetet e Bashkuara të Amerikës',
        'Tajlanda',
        'Tanzania',
        'Taxhikistani',
        'Timori Lindor',
        'Togo',
        'Tonga',
        'Trinidadi dhe Tobagoja',
        'Tunizia',
        'Turkmenistani',
        'Turqia',
        'Tuvalu',
        'Uganda',
        'Ukraina',
        'Uruguaji',
        'Uzbekistani',
        'Vanuatu',
        'Vatikani',
        'Venezuela',
        'Vietnami',
        'Xhamajka',
        'Xhibuti',
        'Zambia',
        'Zelanda e Re',
        'Zimbabveja',
        'Zvicra',
        'Abkazia',
        'Arcah',
        'Doneckut, Republika Popullore e',
        'Kosova',
        'Ishujt Kuk',
        'Luhanskut, Republika Popullore e',
        'Niue',
        'Osetia Jugore',
        'Qiproja Veriore',
        'Sahravit, Republika Demokratike Arabe e',
        'Somalilandi',
        'Tajvan',
        'Transnistria',
    ];

    /**
     * https://en.wikipedia.org/wiki/Municipalities_of_Kosovo
     */
    protected static $municipalities = [
        'Deçan',
        'Dragash',
        'Drenas',
        'Ferizaj',
        'Fushë Kosova',
        'Gjakova',
        'Gjilan',
        'Graçanicë',
        'Hani i Elezit',
        'Istog',
        'Junik',
        'Kaçanik',
        'Kamenica',
        'Klinë',
        'Kllokot',
        'Leposaviq',
        'Lipjan',
        'Malisheva',
        'Mamusha',
        'Mitrovica',
        'North Mitrovica',
        'Novobërda',
        'Obiliq',
        'Partesh',
        'Peja',
        'Podujevë',
        'Prishtina',
        'Prizren',
        'Rahovec',
        'Ranillug',
        'Skenderaj',
        'Shtime',
        'Shtërpca',
        'Suhareka',
        'Vitia',
        'Vushtrri',
        'Zubin Potoku',
        'Zveçan',
    ];

    public static function municipality(): string
    {
        return static::randomElement(static::$municipalities);
    }

    public static function street(): string
    {
        return static::randomElement(static::$street);
    }

    public static function localCoordinates(): array
    {
        return [
            'latitude' => static::latitude(42.245536, 42.852125),
            'longitude' => static::longitude(20.515369, 21.351432),
        ];
    }
}
