<?php

namespace Faker\Provider\sq_AL;

class Address extends \Faker\Provider\Address
{
    protected static $streetPrefix = [
        'Rruga',
        'Bulevardi',
        'Sheshi',
    ];

    protected static $street = [
        'Myslym Shyri',
        'Barrikadave',
        'Sami Frashëri',
        'Ismail Qemali',
        'Abdi Toptani',
        'George W. Bush',
        'Mihal Duri',
        'Don Bosko',
        'Ali Demi',
        'Petro Nini Luarasi',
        'Faik Konica',
        'Margarita Tutulani',
        'Bardhyl',
        'Fortuzi',
        'Vaso Pasha',
        'Qemal Stafa',
        'Hoxha Tahsim',
        'Reshit Çollaku',
        'Pjetër Bogdani',
        'Asim Vokshi',
        'Kajo Karafili',
        'Skënderbej',
        'Tefta Tashko Koço',
        'Mihal Grameno',
    ];

    protected static $cityFormats = [
        '{{municipality}}',
    ];

    protected static $streetNameFormats = [
        '{{street}}',
        '{{streetPrefix}} {{street}}',
    ];

    protected static $streetAddressFormats = [
        '{{streetName}} {{buildingNumber}}',
    ];

    protected static $addressFormats = [
        "{{streetAddress}}\n{{city}} {{postcode}}",
    ];

    protected static $buildingNumber = ['%##', '%#', '%'];

    /**
     * https://en.wikipedia.org/wiki/Postal_codes_in_Albania
     */
    protected static $postcode = ['####'];

    /**
     * https://sq.wikipedia.org/wiki/Lista_e_shteteve
     */
    protected static $country = [
        'Afganistani',
        'Afrika Qendrore',
        'Algjeria',
        'Andorra',
        'Angola',
        'Antigua dhe Barbuda',
        'Arabia Saudite',
        'Argjentina',
        'Armenia',
        'Australia',
        'Austria',
        'Azerbajxhani',
        'Bahamet',
        'Bahreini',
        'Bangladeshi',
        'Barbadosi',
        'Belgjika',
        'Beliza',
        'Benini',
        'Birmania',
        'Bjellorusia',
        'Bolivia',
        'Bosnja dhe Hercegovina',
        'Botsvana',
        'Brazili',
        'Bregu i Fildishtë',
        'Brunei',
        'Bullgaria',
        'Burkina Faso',
        'Burundi',
        'Butani',
        'Çadi',
        'Republika Çeke',
        'Danimarka',
        'Domenika',
        'Republika Dominikane',
        'Egjipti',
        'Ekuadori',
        'Emiratet e Bashkuara Arabe',
        'Eritrea',
        'Estonia',
        'Etiopia',
        'Federata Mikroneziane',
        'Filipinet',
        'Finlanda',
        'Fixhi',
        'Franca',
        'Gaboni',
        'Gambia',
        'Gana',
        'Grenada',
        'Greqia',
        'Guajana',
        'Guatemala',
        'Guinea',
        'Guinea Bisau',
        'Guinea Ekuatoriale',
        'Gjeorgjia',
        'Gjermania',
        'Haiti',
        'Holanda',
        'Hondurasi',
        'Hungaria',
        'India',
        'Indonezia',
        'Iraku',
        'Irani',
        'Irlanda',
        'Islanda',
        'Italia',
        'Izraeli',
        'Japonia',
        'Jemeni',
        'Jordania',
        'Republika Jugafrikane',
        'Kamboxhia',
        'Kameruni',
        'Kanadaja',
        'Katari',
        'Kazakistani',
        'Kenia',
        'Kepi i Gjelbër',
        'Kili',
        'Kina',
        'Kirgizistani',
        'Kiribati',
        'Kolumbia',
        'Komoret',
        'Kongo, Republika e',
        'Kongo, Republika Demokratike e',
        'Koreja e Jugut',
        'Koreja e Veriut',
        'Kosova',
        'Kosta Rika',
        'Kroacia',
        'Kuba',
        'Kuvajti',
        'Laosi',
        'Lesoto',
        'Letonia',
        'Libani',
        'Liberia',
        'Libia',
        'Lihtenshtajni',
        'Lituania',
        'Luksemburgu',
        'Madagaskari',
        'Malajzia',
        'Malavi',
        'Maldivet',
        'Mali',
        'Mali i Zi',
        'Malta',
        'Maroku',
        'Maqedonia e Veriut',
        'Ishujt Marshall',
        'Mauritania',
        'Mauritiusi',
        'Mbretëria e Bashkuar',
        'Anglia',
        'Irlanda Veriore',
        'Skocia',
        'Uellsi',
        'Moldavia',
        'Monako',
        'Mongolia',
        'Mozambiku',
        'Namibia',
        'Naurua',
        'Nepali',
        'Nigeri',
        'Nigeria',
        'Nikaragua',
        'Norvegjia',
        'Omani',
        'Pakistani',
        'Palau',
        'Palestina',
        'Panamaja',
        'Papua Guinea e Re',
        'Paraguaji',
        'Peruja',
        'Polonia',
        'Portugalia',
        'Qiproja',
        'Ruanda',
        'Rumania',
        'Rusia',
        'Salvadori',
        'Samoa',
        'San Marino',
        'Sao Tome dhe Principe',
        'Sejshellet',
        'Senegali',
        'Serbia',
        'Siera Leone',
        'Singapori',
        'Siria',
        'Sllovakia',
        'Sllovenia',
        'Ishujt Solomon',
        'Somalia',
        'Spanja',
        'Sri Lanka',
        'Suazilandi',
        'Sudani',
        'Sudani i Jugut',
        'Suedia',
        'Surinami',
        'Shën Kits dhe Nevis',
        'Shën Luçia',
        'Shën Vincenti dhe Grenadinet',
        'Shqipëria',
        'Shtetet e Bashkuara të Amerikës',
        'Tajlanda',
        'Tanzania',
        'Taxhikistani',
        'Timori Lindor',
        'Togo',
        'Tonga',
        'Trinidadi dhe Tobagoja',
        'Tunizia',
        'Turkmenistani',
        'Turqia',
        'Tuvalu',
        'Uganda',
        'Ukraina',
        'Uruguaji',
        'Uzbekistani',
        'Vanuatu',
        'Vatikani',
        'Venezuela',
        'Vietnami',
        'Xhamajka',
        'Xhibuti',
        'Zambia',
        'Zelanda e Re',
        'Zimbabveja',
        'Zvicra',
        'Abkazia',
        'Arcah',
        'Doneckut, Republika Popullore e',
        'Kosova',
        'Ishujt Kuk',
        'Luhanskut, Republika Popullore e',
        'Niue',
        'Osetia Jugore',
        'Qiproja Veriore',
        'Sahravit, Republika Demokratike Arabe e',
        'Somalilandi',
        'Tajvan',
        'Transnistria',
    ];

    /**
     * https://en.wikipedia.org/wiki/Municipalities_of_Albania
     */
    protected static $municipalities = [
        'Belsh',
        'Berat',
        'Bulqizë',
        'Cërrik',
        'Delvinë',
        'Devoll',
        'Dibër',
        'Dimal',
        'Divjakë',
        'Dropull',
        'Durrës',
        'Elbasan',
        'Fier',
        'Finiq',
        'Fushë-Arrëz',
        'Gjirokastër',
        'Gramsh',
        'Has',
        'Himarë',
        'Kamëz',
        'Kavajë',
        'Këlcyrë',
        'Klos',
        'Kolonjë',
        'Konispol',
        'Korçë',
        'Krujë',
        'Kuçovë',
        'Kukës',
        'Kurbin',
        'Lezhë',
        'Libohovë',
        'Librazhd',
        'Lushnjë',
        'Malësi e Madhe',
        'Mallakastër',
        'Maliq',
        'Mat',
        'Memaliaj',
        'Mirditë',
        'Patos',
        'Peqin',
        'Përmet',
        'Poliçan',
        'Pogradec',
        'Prrenjas',
        'Pukë',
        'Pustec',
        'Roskovec',
        'Rrogozhinë',
        'Sarandë',
        'Selenicë',
        'Shijak',
        'Shkodër',
        'Skrapar',
        'Tepelenë',
        'Tiranë',
        'Tropojë',
        'Vau i Dejës',
        'Vlorë',
        'Vorë',
    ];

    public static function municipality(): string
    {
        return static::randomElement(static::$municipalities);
    }

    public static function streetPrefix(): string
    {
        return static::randomElement(static::$streetPrefix);
    }

    public static function street(): string
    {
        return static::randomElement(static::$street);
    }

    public static function localCoordinates(): array
    {
        return [
            'latitude' => static::latitude(40.208626, 42.193826),
            'longitude' => static::longitude(19.649947, 20.371598),
        ];
    }
}
